window.WIKI_DATA = {
  projectId: "shark-populations",
  favoritesKey: "wiki_favorites_shark-populations",
  sources: [
    { label: "IUCN Red List",    url: "https://www.iucnredlist.org" },
    { label: "CITES Appendices", url: "https://cites.org/eng/app/appendices.php" },
    { label: "Shark Trust",      url: "https://www.sharktrust.org" },
    { label: "NOAA Fisheries",   url: "https://www.fisheries.noaa.gov" },
  ],
  items: [
    {
      id: "great-white",
      commonName: "Great White Shark",
      scientificName: "Carcharodon carcharias",
      statusLabel: "Vulnerable",
      lifePercent: 55,
      photo: "projects/shark-populations/images/white_shark.jpg",
      funFact: "Great white sharks can detect a single drop of blood diluted across 25 gallons of water, and sense the faint electrical fields produced by beating hearts.",
      description: "The great white shark is the world's largest predatory fish, found in cool coastal and offshore waters across the globe. Despite their fearsome reputation, attacks on humans are rare and typically cases of mistaken identity — they strongly prefer fat-rich marine mammals over people.",
      habitat: "Cool coastal and offshore waters globally; coastal and offshore waters of continental and insular shelves, shallow bays, and near pinniped colonies. Recorded at depths to 4,199 ft (1,280 m).",
      diet: "Juveniles feed primarily on fish; adults shift to marine mammals — seals, sea lions, and dolphins — as well as large fish, rays, and sea turtles.",
      size: "Males mature at ~7.8 ft (2.4 m); max confirmed 20.9 ft (6.4 m), possibly exceeding 26 ft (8 m).",
      vitalSigns: [
        { label: "Estimated Population",   value: "~3,500 adults" },
        { label: "Lifespan",               value: "70+ years" },
        { label: "Max Length",             value: "6.4 m (20.9 ft) confirmed",   metric: "6.4 m confirmed",   imperial: "20.9 ft confirmed"  },
        { label: "Max Weight",             value: "~2,000 kg (~4,400 lbs)",       metric: "~2,000 kg",         imperial: "~4,400 lbs"         },
        { label: "Reproductive Rate",      value: "2–10 pups per litter; gestates ~18 months" },
        { label: "Age at Maturity",        value: "~9–10 years (females later)" },
        { label: "Top Speed",              value: "~56 km/h (~35 mph) in bursts", metric: "~56 km/h",          imperial: "~35 mph"            },
        { label: "Ecological Role",        value: "Apex Predator" },
        { label: "Diet",                   value: "Seals, sea lions, dolphins, large fish, rays & sea turtles (adults)" },
        { label: "Population Growth Rate", value: "Very low (< 5% per year)" },
        { label: "Key Senses",             value: "Electroreception (Ampullae of Lorenzini); olfaction detects 1 drop of blood in 100 L of water" },
      ],
      physicalScaleImage: "projects/shark-populations/images/white_shark_size.png",
      habitatImage:       "projects/shark-populations/images/white_shark_habitat.png",
      habitatStats: [
        { label: "Global Range", value: "Temperate, subtropical & tropical oceans worldwide" },
        { label: "Depth Range",  value: "Surface to 1,280 m (4,199 ft)", metric: "Surface to 1,280 m", imperial: "Surface to 4,199 ft" },
      ],
      populationTrend: [
        { year: 1970, value: 10000 },
        { year: 1980, value: 8500 },
        { year: 1990, value: 6800 },
        { year: 2000, value: 5200 },
        { year: 2010, value: 4100 },
        { year: 2020, value: 3500 },
      ],
      preyDeclineRegions: [
        { name: "Mediterranean",  severity: "critical", note: "Bluefin tuna collapse; ~97% fish biomass lost" },
        { name: "N. Atlantic",    severity: "high",     note: "Seal and herring stocks heavily depleted" },
        { name: "N. Pacific",     severity: "high",     note: "Salmon and rockfish populations reduced" },
        { name: "S. Africa",      severity: "medium",   note: "Cape fur seal colonies under moderate pressure" },
        { name: "Australia",      severity: "medium",   note: "Southern bluefin tuna depleted offshore" },
        { name: "S. Atlantic",    severity: "low",      note: "Sea lion and tuna populations more stable" },
      ],
      fishingPressureRegions: [
        { name: "Mediterranean",  severity: "critical", note: "Dense longline and gillnet fleets; minimal enforcement" },
        { name: "N. Atlantic",    severity: "high",     note: "Incidental bycatch in swordfish and tuna longlines" },
        { name: "Australia",      severity: "high",     note: "Government-sanctioned drum lines and shark nets" },
        { name: "N. Pacific",     severity: "high",     note: "Illegal targeted fishing for jaws and fins" },
        { name: "S. Africa",      severity: "medium",   note: "Shark nets at beaches; ongoing bycatch" },
        { name: "S. Atlantic",    severity: "low",      note: "Lower commercial fishing pressure in open waters" },
      ],
      healthMetrics: [
        { label: "IUCN Status",          value: "Vulnerable",                                      trend: "stable" },
        { label: "Population Trend",     value: "Decreasing",                                      trend: "down"   },
        { label: "Habitat Quality",      value: "Moderate — coastal zones under pressure",          trend: null     },
        { label: "Prey Availability",    value: "Declining in key regions",                         trend: "down"   },
        { label: "Fishing Pressure",     value: "High — bycatch and targeted poaching",             trend: "down"   },
        { label: "Protection Coverage",  value: "Partial — CITES Appendix II, some EEZs",          trend: "stable",
          links: [
            { label: "CITES Listing", url: "https://cites.org/eng/app/appendices.php" },
            { label: "IUCN Red List", url: "https://www.iucnredlist.org/species/3855/2878674" },
            { label: "Shark Trust",   url: "https://www.sharktrust.org" },
          ]
        },
      ],
      threats: [
        { name: "Bycatch",             severity: "critical", description: "Caught unintentionally in longlines, gill nets, and drum lines set for other species. The leading cause of mortality globally." },
        { name: "Targeted Poaching",   severity: "high",     description: "Hunted for jaws, teeth, fins, and liver oil. Trophy jaws can fetch tens of thousands of dollars on the black market." },
        { name: "Habitat Degradation", severity: "high",     description: "Coastal development, pollution, and noise reduce the quality of pupping and feeding grounds near seal colonies." },
        { name: "Prey Depletion",      severity: "medium",   description: "Overfishing of pinnipeds and large fish reduces the food base, forcing sharks to travel further and expend more energy." },
        { name: "Climate Change",      severity: "medium",   description: "Warming oceans shift prey distributions, alter migration routes, and may affect juvenile survival in pupping areas." },
      ],
      actionItems: [
        { title: "Support Shark Conservation Organizations", description: "Donate to or volunteer with groups like Shark Trust, Save Our Seas Foundation, and Shark Research Institute that fund research, advocacy, and education.", link: "https://www.sharktrust.org" },
        { title: "Advocate for Stronger Bycatch Regulations", description: "Contact your representatives to support legislation requiring circle hooks, excluder devices, and observer programs on commercial fishing vessels.", link: null },
        { title: "Choose Sustainable Seafood", description: "Use guides from the Monterey Bay Aquarium Seafood Watch program. Avoiding unsustainable fisheries reduces bycatch pressure on shark populations.", link: "https://www.seafoodwatch.org" },
        { title: "Oppose Shark Finning", description: "Refuse to purchase or consume shark fin products, and support restaurants and markets that have pledged not to carry them.", link: null },
        { title: "Spread Accurate Information", description: "Challenge fear-based media portrayals. Sharing science-based facts about shark behavior helps build public support for conservation.", link: null },
      ],
    },
    {
      id: "scalloped-hammerhead",
      commonName: "Scalloped Hammerhead",
      scientificName: "Sphyrna lewini",
      statusLabel: "Critically Endangered",
      lifePercent: 18,
      photo: "projects/shark-populations/images/shark-silhouette.jpg",
      funFact: "Their wide-set eyes grant 360° vertical vision — they can see directly above and below simultaneously, giving them an almost complete view of their surroundings.",
      description: "Named for the scalloped front edge of its distinctive hammer-shaped head (cephalofoil), this species aggregates in huge schools during the day — a rare social behavior among sharks. Their populations have collapsed by over 80% in recent decades, driven almost entirely by the fin trade.",
      habitat: "Tropical and warm temperate seas worldwide; coastal, estuarine, and semi-oceanic",
      diet: "Fish, squid, octopus, and crustaceans",
      size: "Up to 4.3 m (14 ft)",
      threats: [
        { name: "Shark Fin Trade",    severity: "critical", description: "The scalloped hammerhead's distinctive fins are among the most prized in the trade. Demand has driven an 80%+ population collapse, with targeted finning the primary driver of decline." },
        { name: "Bycatch",            severity: "critical", description: "Caught incidentally in tuna and swordfish longline fisheries at extremely high rates. Schools near the surface make them especially vulnerable during daytime aggregations." },
        { name: "Coastal Habitat Loss", severity: "high",  description: "Pups and juveniles rely on shallow estuaries and coastal bays as nursery habitat. Urban development, mangrove loss, and pollution degrade these critical areas." },
        { name: "Climate Change",     severity: "medium",   description: "Warming seas compress preferred temperature bands and shift prey distributions, putting additional pressure on already fragmented populations." },
      ],
    },
    {
      id: "whale-shark",
      commonName: "Whale Shark",
      scientificName: "Rhincodon typus",
      statusLabel: "Endangered",
      lifePercent: 38,
      photo: "projects/shark-populations/images/shark-silhouette.jpg",
      funFact: "The world's largest fish — up to 40 feet long — the whale shark feeds entirely on plankton and small fish, filtering thousands of gallons of water each hour.",
      description: "The whale shark is a slow-moving filter feeder and the largest known fish species on Earth. Each individual has a unique pattern of spots and stripes — like a fingerprint — which researchers use to identify and track them across ocean basins. They are known to peacefully interact with divers.",
      habitat: "Tropical and warm temperate seas worldwide; open ocean and productive coastal areas, especially near upwelling zones",
      diet: "Plankton, fish eggs, krill, small fish, and squid",
      size: "Up to 12 m (40 ft); possibly larger",
      threats: [
        { name: "Ship Strikes",           severity: "high",   description: "Slow-moving and surface-dwelling, whale sharks are frequently struck by vessels. Propeller wounds are documented globally, and strikes often go unreported in open-ocean shipping lanes." },
        { name: "Fishing Gear Entanglement", severity: "high", description: "Large body size does not prevent entanglement in purse seines and gill nets. Feeding aggregations near productive coastal upwelling zones overlap heavily with active fisheries." },
        { name: "Tourism Pressure",       severity: "medium", description: "Unregulated swim-with interactions cause chronic stress, alter feeding behavior, and expose sharks to repeated boat traffic at known aggregation sites." },
        { name: "Plastic Ingestion",      severity: "medium", description: "Filter feeding ingests microplastics and larger debris alongside plankton. Plastic concentrations in surface waters are highest in the tropical feeding grounds this species depends on." },
        { name: "Climate Change",         severity: "medium", description: "Shifting ocean temperatures and declining plankton productivity reduce food availability and force longer migrations between feeding aggregations." },
      ],
    },
    {
      id: "bull-shark",
      commonName: "Bull Shark",
      scientificName: "Carcharhinus leucas",
      statusLabel: "Near Threatened",
      lifePercent: 72,
      photo: "projects/shark-populations/images/shark-silhouette.jpg",
      funFact: "Bull sharks can survive in both salt and fresh water, and have been found more than 2,500 miles up the Amazon River — far from any ocean.",
      description: "Bull sharks are among the most adaptable sharks on Earth, capable of osmoregulating between salt and fresh water. This brings them into frequent contact with humans in rivers and shallow coastal bays. They are considered one of the most dangerous sharks, not because they target people, but because of this habitat overlap.",
      habitat: "Tropical and subtropical coastal waters, river mouths, estuaries, and freshwater river systems worldwide",
      diet: "Fish, rays, sea turtles, dolphins, birds, and other sharks",
      size: "Up to 3.4 m (11 ft); females larger",
      threats: [
        { name: "Targeted Fishing",       severity: "high",   description: "Heavily fished for meat, fins, and liver oil in tropical and subtropical markets. Shallow coastal and riverine habitat makes them easy to intercept with nets and longlines." },
        { name: "Freshwater Habitat Loss", severity: "high",  description: "Dams block river access to nursery areas, while agricultural runoff and urban pollution degrade water quality throughout their freshwater range. Bull sharks depend on low-salinity estuaries to give birth." },
        { name: "Water Quality Degradation", severity: "medium", description: "Chemical pollutants and heavy metals accumulate in coastal and riverine systems where bull sharks forage and pup, affecting juvenile survival and reproductive success." },
        { name: "Bycatch",               severity: "medium",  description: "Incidentally caught in coastal gillnets and longlines targeting other species. Coastal development that concentrates fishing effort near river mouths compounds this pressure." },
      ],
    },
    {
      id: "tiger-shark",
      commonName: "Tiger Shark",
      scientificName: "Galeocerdo cuvier",
      statusLabel: "Near Threatened",
      lifePercent: 68,
      photo: "projects/shark-populations/images/shark-silhouette.jpg",
      funFact: "Tiger sharks have serrated, cockscomb-shaped teeth that can cut through sea turtle shells — one of the only predators capable of cracking that armor.",
      description: "Tiger sharks are apex predators and critically important for maintaining the health of seagrass meadows and coral reef ecosystems. By preying on sea turtles, they prevent overgrazing of seagrass beds. They are notably indiscriminate feeders — their stomachs have been found to contain license plates, tires, and boat parts.",
      habitat: "Tropical and subtropical waters worldwide; coastal, reef, and open ocean environments",
      diet: "Sea turtles, fish, marine mammals, seabirds, rays, and almost any other prey item",
      size: "Up to 5.5 m (18 ft)",
      threats: [
        { name: "Targeted Fishing",       severity: "high",   description: "Fins are among the most valuable in the shark fin trade, and liver oil is used in cosmetics and supplements. Demand drives directed fishing across the Indo-Pacific and Atlantic." },
        { name: "Bycatch",               severity: "high",   description: "Frequently caught incidentally in pelagic longlines, gillnets, and drum lines targeting tuna and billfish. Wide-ranging movements across ocean basins increase exposure to diverse fisheries." },
        { name: "Lethal Culling Programs", severity: "high",  description: "Government-sanctioned drum line and shark net programs in Australia and Hawaii kill hundreds of tiger sharks annually to reduce perceived risk to swimmers, with limited evidence of effectiveness." },
        { name: "Habitat Pressures",     severity: "low",    description: "Coastal development and reef degradation reduce prey availability in nearshore habitats, but wide-ranging oceanic behavior provides some buffer against localized habitat loss." },
      ],
    },
  ],
};
