window.WIKI_DATA = {
  projectId: "shark-populations",
  favoritesKey: "wiki_favorites_shark-populations",
  items: [
    {
      id: "great-white",
      commonName: "Great White Shark",
      scientificName: "Carcharodon carcharias",
      statusLabel: "Vulnerable",
      lifePercent: 55,
      photo: null,
      funFact: "Great white sharks can detect a single drop of blood diluted across 25 gallons of water, and sense the faint electrical fields produced by beating hearts.",
      description: "The great white shark is the world's largest predatory fish, found in cool coastal and offshore waters across the globe. Despite their fearsome reputation, attacks on humans are rare and typically cases of mistaken identity — they strongly prefer fat-rich marine mammals over people.",
      habitat: "Cool coastal and offshore waters globally; common off South Africa, Australia, and California",
      diet: "Marine mammals (seals, sea lions), large fish, rays, and occasionally sea turtles",
      size: "Up to 6 m (20 ft); females larger than males",
      threats: "Bycatch in commercial fisheries, targeted poaching for jaws and fins, habitat degradation, and prey depletion",
    },
    {
      id: "scalloped-hammerhead",
      commonName: "Scalloped Hammerhead",
      scientificName: "Sphyrna lewini",
      statusLabel: "Critically Endangered",
      lifePercent: 18,
      photo: null,
      funFact: "Their wide-set eyes grant 360° vertical vision — they can see directly above and below simultaneously, giving them an almost complete view of their surroundings.",
      description: "Named for the scalloped front edge of its distinctive hammer-shaped head (cephalofoil), this species aggregates in huge schools during the day — a rare social behavior among sharks. Their populations have collapsed by over 80% in recent decades, driven almost entirely by the fin trade.",
      habitat: "Tropical and warm temperate seas worldwide; coastal, estuarine, and semi-oceanic",
      diet: "Fish, squid, octopus, and crustaceans",
      size: "Up to 4.3 m (14 ft)",
      threats: "Highly prized fins in the shark fin trade, bycatch in tuna and swordfish longline fisheries, coastal habitat loss",
    },
    {
      id: "whale-shark",
      commonName: "Whale Shark",
      scientificName: "Rhincodon typus",
      statusLabel: "Endangered",
      lifePercent: 38,
      photo: null,
      funFact: "The world's largest fish — up to 40 feet long — the whale shark feeds entirely on plankton and small fish, filtering thousands of gallons of water each hour.",
      description: "The whale shark is a slow-moving filter feeder and the largest known fish species on Earth. Each individual has a unique pattern of spots and stripes — like a fingerprint — which researchers use to identify and track them across ocean basins. They are known to peacefully interact with divers.",
      habitat: "Tropical and warm temperate seas worldwide; open ocean and productive coastal areas, especially near upwelling zones",
      diet: "Plankton, fish eggs, krill, small fish, and squid",
      size: "Up to 12 m (40 ft); possibly larger",
      threats: "Ship strikes, entanglement in fishing gear, tourism pressure, plastic ingestion, and climate-driven changes to plankton availability",
    },
    {
      id: "bull-shark",
      commonName: "Bull Shark",
      scientificName: "Carcharhinus leucas",
      statusLabel: "Near Threatened",
      lifePercent: 72,
      photo: null,
      funFact: "Bull sharks can survive in both salt and fresh water, and have been found more than 2,500 miles up the Amazon River — far from any ocean.",
      description: "Bull sharks are among the most adaptable sharks on Earth, capable of osmoregulating between salt and fresh water. This brings them into frequent contact with humans in rivers and shallow coastal bays. They are considered one of the most dangerous sharks, not because they target people, but because of this habitat overlap.",
      habitat: "Tropical and subtropical coastal waters, river mouths, estuaries, and freshwater river systems worldwide",
      diet: "Fish, rays, sea turtles, dolphins, birds, and other sharks",
      size: "Up to 3.4 m (11 ft); females larger",
      threats: "Targeted fishing for meat and fins, habitat loss in river systems from dams and pollution, water quality degradation",
    },
    {
      id: "tiger-shark",
      commonName: "Tiger Shark",
      scientificName: "Galeocerdo cuvier",
      statusLabel: "Near Threatened",
      lifePercent: 68,
      photo: null,
      funFact: "Tiger sharks have serrated, cockscomb-shaped teeth that can cut through sea turtle shells — one of the only predators capable of cracking that armor.",
      description: "Tiger sharks are apex predators and critically important for maintaining the health of seagrass meadows and coral reef ecosystems. By preying on sea turtles, they prevent overgrazing of seagrass beds. They are notably indiscriminate feeders — their stomachs have been found to contain license plates, tires, and boat parts.",
      habitat: "Tropical and subtropical waters worldwide; coastal, reef, and open ocean environments",
      diet: "Sea turtles, fish, marine mammals, seabirds, rays, and almost any other prey item",
      size: "Up to 5.5 m (18 ft)",
      threats: "Targeted fishing for fins and liver oil, bycatch, and lethal culling programs in Australia and Hawaii",
    },
  ],
};
