window.WIKI_DATA = {
  projectId: "shark-populations",
  favoritesKey: "wiki_favorites_shark-populations",
  items: [
    {
      id: "great-white",
      commonName: "Great White Shark",
      scientificName: "Carcharodon carcharias",
      statusLabel: "Vulnerable",
      lifePercent: 55,
      photo: "projects/shark-populations/images/white_shark.jpg",
      funFact: "Great white sharks can detect a single drop of blood diluted across 25 gallons of water, and sense the faint electrical fields produced by beating hearts.",
      description: "The great white shark is the world's largest predatory fish, found in cool coastal and offshore waters across the globe. Despite their fearsome reputation, attacks on humans are rare and typically cases of mistaken identity — they strongly prefer fat-rich marine mammals over people.",
      habitat: "Cool coastal and offshore waters globally; coastal and offshore waters of continental and insular shelves, shallow bays, and near pinniped colonies. Recorded at depths to 4,199 ft (1,280 m).",
      diet: "Juveniles feed primarily on fish; adults shift to marine mammals — seals, sea lions, and dolphins — as well as large fish, rays, and sea turtles.",
      size: "Males mature at ~7.8 ft (2.4 m); max confirmed 20.9 ft (6.4 m), possibly exceeding 26 ft (8 m).",
      vitalSigns: [
        { label: "Estimated Population", value: "~3,500 adults" },
        { label: "Lifespan",             value: "70+ years" },
        { label: "Max Length",           value: "6.4 m (20.9 ft) confirmed" },
        { label: "Max Weight",           value: "~2,000 kg (4,400 lbs)" },
        { label: "Reproductive Rate",    value: "2–10 pups per litter; gestates ~18 months" },
        { label: "Age at Maturity",      value: "~9–10 years (females later)" },
      ],
      physicalScaleImage: "projects/shark-populations/images/white_shark_size.png",
      habitatImage:       "projects/shark-populations/images/white_shark_habitat.png",
      habitatStats: [
        { label: "Global Range", value: "Temperate, subtropical & tropical oceans worldwide" },
        { label: "Depth Range",  value: "Surface to 1,280 m (4,199 ft)" },
      ],
      healthMetrics: [
        { label: "IUCN Status",          value: "Vulnerable",                                      trend: "stable" },
        { label: "Population Trend",     value: "Decreasing",                                      trend: "down"   },
        { label: "Habitat Quality",      value: "Moderate — coastal zones under pressure",          trend: null     },
        { label: "Prey Availability",    value: "Declining in key regions",                         trend: "down"   },
        { label: "Fishing Pressure",     value: "High — bycatch and targeted poaching",             trend: "down"   },
        { label: "Protection Coverage",  value: "Partial — CITES Appendix II, some EEZs",          trend: "stable" },
      ],
      threats: [
        { name: "Bycatch",             severity: "critical", description: "Caught unintentionally in longlines, gill nets, and drum lines set for other species. The leading cause of mortality globally." },
        { name: "Targeted Poaching",   severity: "high",     description: "Hunted for jaws, teeth, fins, and liver oil. Trophy jaws can fetch tens of thousands of dollars on the black market." },
        { name: "Habitat Degradation", severity: "high",     description: "Coastal development, pollution, and noise reduce the quality of pupping and feeding grounds near seal colonies." },
        { name: "Prey Depletion",      severity: "medium",   description: "Overfishing of pinnipeds and large fish reduces the food base, forcing sharks to travel further and expend more energy." },
        { name: "Climate Change",      severity: "medium",   description: "Warming oceans shift prey distributions, alter migration routes, and may affect juvenile survival in pupping areas." },
      ],
      actionItems: [
        { title: "Support Shark Conservation Organizations", description: "Donate to or volunteer with groups like Shark Trust, Save Our Seas Foundation, and Shark Research Institute that fund research, advocacy, and education.", link: "https://www.sharktrust.org" },
        { title: "Advocate for Stronger Bycatch Regulations", description: "Contact your representatives to support legislation requiring circle hooks, excluder devices, and observer programs on commercial fishing vessels.", link: null },
        { title: "Choose Sustainable Seafood", description: "Use guides from the Monterey Bay Aquarium Seafood Watch program. Avoiding unsustainable fisheries reduces bycatch pressure on shark populations.", link: "https://www.seafoodwatch.org" },
        { title: "Oppose Shark Finning", description: "Refuse to purchase or consume shark fin products, and support restaurants and markets that have pledged not to carry them.", link: null },
        { title: "Spread Accurate Information", description: "Challenge fear-based media portrayals. Sharing science-based facts about shark behavior helps build public support for conservation.", link: null },
      ],
    },
    {
      id: "scalloped-hammerhead",
      commonName: "Scalloped Hammerhead",
      scientificName: "Sphyrna lewini",
      statusLabel: "Critically Endangered",
      lifePercent: 18,
      photo: null,
      funFact: "Their wide-set eyes grant 360° vertical vision — they can see directly above and below simultaneously, giving them an almost complete view of their surroundings.",
      description: "Named for the scalloped front edge of its distinctive hammer-shaped head (cephalofoil), this species aggregates in huge schools during the day — a rare social behavior among sharks. Their populations have collapsed by over 80% in recent decades, driven almost entirely by the fin trade.",
      habitat: "Tropical and warm temperate seas worldwide; coastal, estuarine, and semi-oceanic",
      diet: "Fish, squid, octopus, and crustaceans",
      size: "Up to 4.3 m (14 ft)",
      threats: "Highly prized fins in the shark fin trade, bycatch in tuna and swordfish longline fisheries, coastal habitat loss",
    },
    {
      id: "whale-shark",
      commonName: "Whale Shark",
      scientificName: "Rhincodon typus",
      statusLabel: "Endangered",
      lifePercent: 38,
      photo: null,
      funFact: "The world's largest fish — up to 40 feet long — the whale shark feeds entirely on plankton and small fish, filtering thousands of gallons of water each hour.",
      description: "The whale shark is a slow-moving filter feeder and the largest known fish species on Earth. Each individual has a unique pattern of spots and stripes — like a fingerprint — which researchers use to identify and track them across ocean basins. They are known to peacefully interact with divers.",
      habitat: "Tropical and warm temperate seas worldwide; open ocean and productive coastal areas, especially near upwelling zones",
      diet: "Plankton, fish eggs, krill, small fish, and squid",
      size: "Up to 12 m (40 ft); possibly larger",
      threats: "Ship strikes, entanglement in fishing gear, tourism pressure, plastic ingestion, and climate-driven changes to plankton availability",
    },
    {
      id: "bull-shark",
      commonName: "Bull Shark",
      scientificName: "Carcharhinus leucas",
      statusLabel: "Near Threatened",
      lifePercent: 72,
      photo: null,
      funFact: "Bull sharks can survive in both salt and fresh water, and have been found more than 2,500 miles up the Amazon River — far from any ocean.",
      description: "Bull sharks are among the most adaptable sharks on Earth, capable of osmoregulating between salt and fresh water. This brings them into frequent contact with humans in rivers and shallow coastal bays. They are considered one of the most dangerous sharks, not because they target people, but because of this habitat overlap.",
      habitat: "Tropical and subtropical coastal waters, river mouths, estuaries, and freshwater river systems worldwide",
      diet: "Fish, rays, sea turtles, dolphins, birds, and other sharks",
      size: "Up to 3.4 m (11 ft); females larger",
      threats: "Targeted fishing for meat and fins, habitat loss in river systems from dams and pollution, water quality degradation",
    },
    {
      id: "tiger-shark",
      commonName: "Tiger Shark",
      scientificName: "Galeocerdo cuvier",
      statusLabel: "Near Threatened",
      lifePercent: 68,
      photo: null,
      funFact: "Tiger sharks have serrated, cockscomb-shaped teeth that can cut through sea turtle shells — one of the only predators capable of cracking that armor.",
      description: "Tiger sharks are apex predators and critically important for maintaining the health of seagrass meadows and coral reef ecosystems. By preying on sea turtles, they prevent overgrazing of seagrass beds. They are notably indiscriminate feeders — their stomachs have been found to contain license plates, tires, and boat parts.",
      habitat: "Tropical and subtropical waters worldwide; coastal, reef, and open ocean environments",
      diet: "Sea turtles, fish, marine mammals, seabirds, rays, and almost any other prey item",
      size: "Up to 5.5 m (18 ft)",
      threats: "Targeted fishing for fins and liver oil, bycatch, and lethal culling programs in Australia and Hawaii",
    },
  ],
};
